config/routes.rb
Housemates::Application.routes.draw do

  resources :notes, except: [:index, :show, :new] do
    member do
      get :cancel_edit
    end
  end

  resources :houses, except: :new do
    member do
      get :join
      get :leave
      get :add
    end

    collection do
      get :move_in
      get :pre_join
      get :pre_add
    end
  end

  devise_for :people

  authenticated :person do
    root to: "houses#index"
  end

  root to: "welcome#index"

end

app/models/house.rb
class House < ActiveRecord::Base
	# Mass-assignments
  attr_accessible :name, :public

  # Associations
  has_many :people
  has_many :notes
  has_many :memberships
  has_many :people, through: :memberships

  # Validations
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :public, inclusion: { in: [true, false] }
end

app/models/membership.rb
class Membership < ActiveRecord::Base
	#Associations
  belongs_to :house
  belongs_to :person
end

app/models/note.rb
class Note < ActiveRecord::Base
  #Mass-assignments
  attr_accessible :text, :person_id, :house_id

  #Associations
  belongs_to :person
  belongs_to :house

  # Validations
  validates :text, :person_id, :house_id, presence: true
end

app/models/person.rb
class Person < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :public

  # Associations
  has_many :memberships
  has_many :houses, through: :memberships

  # Validations
  validates :name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :public, inclusion: { in: [true, false] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate_person!

  protect_from_forgery
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  # GET /houses
  # GET /houses.json
  def index
    if current_person.houses.empty?
      redirect_to move_in_houses_path
    else
      @houses = current_person.houses
      @house = House.new

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @houses }
      end
    end
  end

  # GET /houses/1
  # GET /houses/1.json
  def show
    @house = House.find(params[:id])
    @notes = @house.notes.order('updated_at DESC')
    @note = Note.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @house }
    end
  end

  # GET /houses/1/edit
  def edit
    @house = House.find(params[:id])
  end

  # POST /houses
  # POST /houses.json
  def create
    @house = House.new(params[:house])

    respond_to do |format|
      if @house.save
        current_person.houses << @house
        format.html { redirect_to root_path, notice: 'House was successfully created.' }
        format.json { render json: @house, status: :created, location: @house }
      else
        format.html { render action: "new" }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /houses/1
  # PUT /houses/1.json
  def update
    @house = House.find(params[:id])

    respond_to do |format|
      if @house.update_attributes(params[:house])
        format.html { redirect_to @house, notice: 'House was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house = House.find(params[:id])
    @house.destroy

    respond_to do |format|
      format.html { redirect_to houses_url }
      format.json { head :no_content }
    end
  end

  def move_in
    @houses = House.all
    @house = House.new
  end

  def pre_join
    @house = House.where('lower(name) = ?', params[:name].downcase).first
    redirect_to action: :join, id: @house.to_param
  end

  def pre_add
    @person = Person.where('lower(email) = ?', params[:email].downcase).first
    #@house = House.find()
    redirect_to action: :add, id: params[:house_id],
                flash: { person_id: @person.to_param }
  end

  def join
    @house = House.find(params[:id])
    current_person.houses << @house

    respond_to do |format|
      if @house.update_attributes(params[:house])
        format.html { redirect_to root_path, notice: 'Successfully moved in.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  def add
    @house = House.find(params[:id])
    @person = Person.find(params[:flash][:person_id])
    @person.houses << @house

    respond_to do |format|
      if @house.update_attributes(params[:house])
        format.html { redirect_to @house, notice: 'Successfully moved in.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  def leave
    @house = House.find(params[:id])
    current_person.houses.delete(@house)
    redirect_to root_path
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def edit
    @note = Note.find(params[:id])

    respond_to do |format|
      format.js
    end
  end

  def cancel_edit
    @note = Note.find(params[:id])

    respond_to do |format|
      format.js
    end
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(params[:note])

    respond_to do |format|
      if @note.save
        format.html { redirect_to house_path(@note.house_id), notice: 'Note was successfully created.' }
        format.json { render json: @note, status: :created, location: @note }
      else
        format.html { render action: "new" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.json
  def update
    @note = Note.find(params[:id])

    if params[:submit_button]
      respond_to do |format|
        if @note.update_attributes(params[:note])
          format.html { redirect_to house_path(@note.house_id), notice: 'Note was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @note.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.js { render action: :cancel_edit, id: @note.to_param }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    respond_to do |format|
      format.html { redirect_to house_path(@note.house_id) }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_filter :authenticate_person!

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :person
  end
 
  def resource
    @resource ||= Person.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:person]
  end

  def gravatar_for(user, size=30)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/houses/_form.html.erb
<%= form_for(@house) do |f| %>
  <% if @house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
      <% @house.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :name, class: "input-block-level", placeholder: "House name" %>
  <%= f.label :public, class: "checkbox" do %>
    <%= f.check_box :public %> Anyone can move into the house, no approval necessary
  <% end %>
  <% if new_house %>
    <%= f.submit "Create house and move in", class: "btn" %>
  <% else %>
    <%= f.submit "Save", class: "btn" %>
  <% end %>
  
<% end %>

app/views/houses/_house.html.erb
<li class="span4 note-cell">
  <div class="thumbnail">
  	<!--Header-->
    <div class="row-fluid cell-header">
      <div class="span9">
        <h4><%= link_to house.name, house %></h4>
        <small class="byline"><%= pluralize house.people.count, 'resident' %></small>
      </div>
      <div class="span3 text-right">
        <div id="house-option-links">
          <%= link_to raw('<i class="icon-wrench"></i>'),
                      edit_house_path(house) %>
          <%= link_to raw('<i class="icon-remove"></i>'),
                      '#confirm-delete-house', id: 'delete-house-link',
                      data: { path: "../houses/#{house.id}", toggle: 'modal' } %>
        </div>
      </div>
    </div>

    <!--Body-->
    <div class="row-fluid">
      <% house.people.take(5).each do |resident| %>
        <%= gravatar_for resident %>
      <% end %>
    </div>
  </div>
</li>

app/views/houses/_move_in_form.html.erb
<p class="lead text-center">Join an existing house</p>
<%= form_tag pre_join_houses_path, method: "get" do %>
  <%= text_field_tag :name, nil, class: "input-block-level", placeholder: "Enter house name" %>
  <%= submit_tag "Move in", class: "btn btn-primary" %>
<% end %>

<hr>
<p class="lead text-center">or create a new one</p>
<%= render partial: 'form', locals: { new_house: true } %> 

app/views/houses/edit.html.erb
<h1>Editing house</h1>

<%= render partial: 'form', locals: { new_house: false } %>

<%= link_to 'Show', @house %> |
<%= link_to 'Back', houses_path %>

app/views/houses/index.html.erb
<div class="row-fluid">
  <div class="span8">
    <!--List of user's houses-->
    <ul class="thumbnails" id="editable-list">
      <%= render @houses %>
    </ul>

    <!--Confirm delete dialog-->
    <div class="modal hide fade" id="confirm-delete-house">
      <div class="modal-header">
        <h3>Confirm Delete</h3>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete this?</p>
      </div>
      <div class="modal-footer">
        <%= link_to 'Delete', 'path', method: :delete,
                    class: 'btn btn-primary', id: 'delete-button' %>
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
      </div>
    </div>
  </div>

  <!--Sidebar: Join/create house form-->
  <div class="span4 well">
    <%= render 'move_in_form' %>
  </div>
</div>

app/views/houses/move_in.html.erb
<div class="row-fluid">
  <div class="medium-center-container">
    <h2 class="text-center">Move into a house to start using Housemates</h2>
    <br>

    <%= render 'move_in_form' %>

  </div>
</div>

app/views/houses/show.html.erb
<div class="row-fluid">
  <div class="span8">
    <ul class="thumbnails" id="editable-list">
      <!--Create note form-->
      <li class="span4">
        <div class="thumbnail">
          <%= render 'notes/new' %>
        </div>
      </li>

      <!--List of house's notes-->
      <%= render @notes %>

    </ul>

    <!--Confirm delete dialog-->
    <div class="modal hide fade" id="confirm-delete">
      <div class="modal-header">
        <h3>Confirm Delete</h3>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete this?</p>
      </div>
      <div class="modal-footer">
        <%= link_to 'Delete', 'path', method: :delete,
                    class: 'btn btn-primary', id: 'delete-button' %>
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
      </div>
    </div>
    
  </div>

  <!--Sidebar: House info-->
  <div class="span4 well">
    <h3><%= @house.name %></h3>
    <hr>
    <% @house.people.each do |resident| %>
      <p><%= gravatar_for resident %>
      <%= resident.name %></p>
    <% end %>

    <p>
      <%= form_tag pre_add_houses_path, method: "get" do %>
        <%= text_field_tag :email, nil, class: "input-block-level",
                           placeholder: "Enter email to add a housemate" %>
        <%= hidden_field_tag :house_id, @house.id %>
        <%= submit_tag "Add", class: "btn btn-warning" %>
      <% end %>
    </p>

    <p>
      <%= link_to raw('<i class="icon-briefcase"></i> Move out'),
                  leave_house_path(@house) %>
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Housemates</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
	<div class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container">
 
        <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
        <!--TODO: Use link_to instead?-->
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
 
        <!-- Be sure to leave the brand out there if you want it shown -->
        <%= link_to 'housemates', root_path, class: 'brand' %>
        <!--<a class="brand" href="#">housemates</a>-->
 
        <!-- Everything you want hidden at 940px or less, place within here -->
        <div class="nav-collapse collapse">
          <!-- .nav, .navbar-search, .navbar-form, etc -->
          <% if person_signed_in? %>
            <%= render "shared/navbar" %>
          <% else %>
            <%= render "welcome/navbar" %>
          <% end %>
        </div>
 
      </div>
    </div>
  </div>

  <div class="container-fluid">
    <% if notice %><p class="notice"><%= notice %></p><% end %>
    <% if alert %><p class="alert"><%= alert %></p><% end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/notes/_edit.html.erb
<%= render partial: 'notes/form',
           locals: { submit_url: 'note_path(@note)',
                     button_text: 'Save',
                     button_class: 'btn btn-warning',
                     new_note: false } %>

app/views/notes/_form.html.erb
<%= form_for @note do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_area :text, rows: 5, placeholder: "Type a new note" %>
  <%= f.hidden_field :person_id, value: current_person.id %>
  <% if new_note %>
    <%= f.hidden_field :house_id, value: @house.id %>
  <% end %>
  <%= f.submit button_text, name: 'submit_button',class: button_class %>
  <% unless new_note %>
    <%= f.submit "Cancel", name: 'cancel_button',
                 class: "btn", id: 'cancel-edit-button' %>
  <% end %>
<% end %>

app/views/notes/_new.html.erb
<%= render partial: 'notes/form',
           locals: { submit_url: 'notes_path',
                     button_text: 'Post',
                     button_class: 'btn btn-primary',
                     new_note: true } %>

app/views/notes/_note.html.erb
<li class="span4 note-cell">
  <div class="thumbnail" id="note-container">
    <%= render partial: "notes/show", locals: {note: note} %>
  </div>
</li>

app/views/notes/_show.html.erb
<!--Note header-->
<div class="row-fluid cell-header">
  <div class="span9">
    <h4><%= note.person.name %></h4>
    <small class="byline"><%= note.updated_at.strftime "%b %e, %Y at %l:%M%P" %></small>
  </div>
  <div class="span3 text-right">
    <div id="option-links">
      <%= link_to raw('<i class="icon-pencil" id="edit-note-link"></i>'),
                  edit_note_path(note),
                  remote: true %>
      <%= link_to raw('<i class="icon-remove"></i>'),
                  '#confirm-delete', id: 'delete-link',
                  data: { path: "../notes/#{note.id}", toggle: 'modal' } %>
    </div>
  </div>
</div>

<!--Note body-->
<div class="row-fluid">
  <%= note.text %>
</div>

app/views/notes/cancel_edit.js.erb
$ ('#current-edit-note-container').html('<%= j render(partial: "show",
                                                      locals: { note: @note }) %>')
                                  .attr('id', 'note-container');

app/views/notes/edit.js.erb
$ ('#current-note-container').html('<%= j render(partial: "edit",
                                                 locals: { note: @note }) %>')
                             .attr('id', 'edit-note-container');

app/views/shared/_navbar.html.erb
<!--Main menu-->
<ul class="nav">
  <li><%= link_to 'Home', '#' %></li>
  <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to 'My Houses', root_path %></li>
</ul>

<!--Dropdown menu-->
<ul class="nav pull-right">
  <li class="dropdown">
    <%= link_to '#', class: "dropdown-toggle",
                data: { toggle: "dropdown" } do %>
      <%= gravatar_for current_person %>
      <%= current_person.name %>
      <b class="caret"></b>
    <% end %>

    <ul class="dropdown-menu">
      <li><%= link_to 'Profile', '#' %></li>
      <li><%= link_to 'Settings', edit_person_registration_path %></li>
      <li><%= link_to 'Log Out', destroy_person_session_path, method: :delete %></li>
    </ul>
  </li>
</ul>

app/views/welcome/_navbar.html.erb
<%= form_for resource,
             as: resource_name,
             url: session_path(resource_name),
             html: { class: "navbar-form pull-right" } do |f| %>
              
  <%= f.email_field :email, class: "span2", placeholder: "Email" %>

  <%= f.password_field :password, class: "span2", placeholder: "Password" %>

  <% if devise_mapping.rememberable? -%>
    <%= f.label :remember_me, class: "checkbox inline" do %>
    <%= f.check_box :remember_me %>
      <div class="remember-me">Remember me</div>
    <% end %>
  <% end -%>

  <%= f.submit "Sign in", class: "btn" %>
<% end %>

app/views/welcome/index.html.erb
<div class="row-fluid">
  <div class="span8">
    <!--Body content-->
    <br><br>
    <div class="box-container">
      <div class="box box-leftmost"><%= fa_icon "file-text inverse" %></div>
      <div class="box"><h1>Add notes</h1></div>
      <div class="box"><%= fa_icon "share inverse" %></div>
      <div class="box box-leftmost"><h1>Manage multiple boards</h1></div>
      <div class="box"><%= fa_icon "th inverse" %></div>
      <div class="box"><h1>Share with friends</h1></div>
      <div class="box-leftmost"><br></div>
    </div>
  </div>
  <div class="span4">
    <!--Sidebar content, move to partial shared/sign_up_form-->
<%= form_for resource,
             as: resource_name,
             url: registration_path(resource_name),
             html: { class: "well" } do |f| %>
  <h2>Sign up</h2>

  <%= devise_error_messages! %>
              
  <%= f.text_field :name, class: "input-block-level", placeholder: "Full name" %>

  <%= f.email_field :email, class: "input-block-level", placeholder: "Email address" %>

  <%= f.password_field :password, class: "input-block-level", placeholder: "Password" %>

  <%= f.password_field :password_confirmation, class: "input-block-level", placeholder: "Confirm password" %>

  <%= f.label :public, class: "checkbox" do %>
    <%= f.check_box :public %> Make profile public
  <% end %>

  <%= f.submit "Sign up", class: "btn btn-large btn-primary" %>

  <br><br><%= render "devise/shared/links" %>
<% end %>
  </div>
</div>